"""
ARMA Models: Autoregressive Moving Average Time Series Models
=============================================================

Explores Autoregressive Moving Average (ARMA) models including:
  - Differencing and stationarity (backshift operator)
  - AR(p) models: simulation and properties
  - MA(q) models: simulation and properties
  - ARMA(p, q) models: simulation, causality, and invertibility
  - Estimation methods and forecasting theory

Reference: Chapters 3 and 4 from "Applied Time Series Analysis and Forecasting
with Python" (Huang & Petukhina, 2022).

Source: "quantitative-finance-notebooks" collection.
"""

import numpy as np
import scipy.stats as ss
import matplotlib.pyplot as plt


# =============================================================================
# 1. Differencing and Stationarity
# =============================================================================
#
# The backshift (or lag) operator operates on a time series {X_t}.
# Using B for backshift, we define:
#
#     B X_t = X_{t-1}
#
# Generally:
#     B^n X_t = X_{t-n}   for any integer n >= 1, and B^0 X_t = X_t.
#
# Using B, the random walk can be written as (1 - B) X_t = W_t
# where W_t ~ WN(0, sigma^2).
#
# Differencing makes a nonstationary time series stationary by computing
# differences between consecutive values.
#
# Order-d differencing:
#     nabla^1 X_t = (1 - B) X_t = X_t - X_{t-1}
#     nabla^d X_t = (1 - B)^d X_t                        (1.1)
#
# Lag-k differencing:
#     nabla_k X_t = (1 - B^k) X_t = X_t - X_{t-k}       (1.2)
#
# If lag k is the number of seasons, lag-k differencing is seasonal
# differencing. Note: nabla^d != nabla_d except for d = 1.
#
# Strategy:
#   - Trend but no seasonality: use d-th order differencing.
#   - Seasonality present: do seasonal differencing first, then check
#     if additional d-th order differencing is needed.


# =============================================================================
# 2. Autoregressive Moving Average Models
# =============================================================================

# -----------------------------------------------------------------------------
# 2.1 AR Models
# -----------------------------------------------------------------------------
#
# The autoregressive model of order p, denoted AR(p):
#
#     X_t = phi_0 + phi_1 X_{t-1} + phi_2 X_{t-2} + ... + phi_p X_{t-p} + eps_t
#                                                                       (2.1.1)
#
# where {eps_t} ~ WN(0, sigma_eps^2), E(X_s eps_t) = 0 if s < t, and
# phi_0, phi_1, ..., phi_p are real-valued parameters with phi_p != 0.
#
# Notes:
#   - For simplicity, we often assume phi_0 = 0; otherwise consider
#     {X_t - mu} where mu = phi_0 / (1 - phi_1 - ... - phi_p).
#   - AR models may or may not be stationary; AR processes must be stationary.
#   - E(X_s eps_t) = 0 (s < t) means past X_s is independent of current eps_t.
#   - eps_t is also called the innovation or shock term.
#   - AR(p) has the same form as multiple linear regression but explains the
#     current value with its own past.
#
# Using the backshift operator B:
#     phi(B) X_t = eps_t
# where phi(z) = 1 - phi_1 z - ... - phi_p z^p is the AR polynomial.

# Simulate AR(2): X_t = 0.8 X_{t-1} - 0.3 X_{t-2} + eps_t
# where eps_t ~ iidN(0, 1), sample size N = 200.
N = 200
X = np.zeros(N)
phi_1, phi_2 = 0.8, -0.3
epsilon = ss.norm.rvs(loc=0, scale=1, size=N, random_state=42)
for t in range(2, N):
    X[t] = phi_1 * X[t - 1] + phi_2 * X[t - 2] + epsilon[t]

# Plot the sample path
plt.figure(figsize=(6, 3))
plt.plot(X, color='C2')
plt.title('AR(2) Sample Path')
plt.xlabel('N')
plt.grid(True)
plt.show()


# -----------------------------------------------------------------------------
# 2.2 MA Models
# -----------------------------------------------------------------------------
#
# The moving average model of order q, denoted MA(q):
#
#     X_t = mu + eps_t + theta_1 eps_{t-1} + ... + theta_q eps_{t-q}   (2.2.1)
#
# where {eps_t} ~ WN(0, sigma_eps^2) and mu, theta_1, ..., theta_q are
# real-valued parameters with theta_q != 0.
#
# Notes:
#   - For simplicity, we often assume mu = 0; otherwise consider {X_t - mu}.
#     Note: E(X_t) = mu.
#   - The series generated by MA(q) is obviously always stationary.
#
# Using the backshift operator B:
#     X_t = theta(B) eps_t
# where theta(z) = 1 + theta_1 z + ... + theta_q z^q is the MA polynomial.

# Simulate MA(2): X_t = eps_t + 0.6 eps_{t-1} - 0.3 eps_{t-2}
# where eps_t ~ iidN(0, 1), sample size N = 200.
N = 200
X = np.zeros(N)
theta_1, theta_2 = 0.6, -0.3
epsilon = ss.norm.rvs(loc=0, scale=1, size=N, random_state=42)
for t in range(2, N):
    X[t] = epsilon[t] + theta_1 * epsilon[t - 1] + theta_2 * epsilon[t - 2]

# Plot the sample path
plt.figure(figsize=(6, 3))
plt.plot(X, color='C3')
plt.title('MA(2) Sample Path')
plt.xlabel('N')
plt.grid(True)
plt.show()


# -----------------------------------------------------------------------------
# 2.3 ARMA Models
# -----------------------------------------------------------------------------
#
# The autoregressive moving average model of order (p, q), denoted ARMA(p, q):
#
#     X_t = phi_0 + phi_1 X_{t-1} + ... + phi_p X_{t-p}
#           + theta_1 eps_{t-1} + ... + theta_q eps_{t-q} + eps_t      (2.3.1)
#
# where {eps_t} ~ WN(0, sigma_eps^2), E(X_s eps_t) = 0 if s < t,
# and {phi_k}, {theta_k} are real-valued parameters with phi_p != 0
# and theta_q != 0.
#
# In sigma notation:
#     X_t = phi_0 + sum_{i=1}^{p} phi_i X_{t-i}
#           + sum_{j=1}^{q} theta_j eps_{t-j} + eps_t
#
# Using the backshift operator B:
#     phi(B) X_t = theta(B) eps_t
# where phi(z) = 1 - phi_1 z - ... - phi_p z^p  is the AR polynomial
# and   theta(z) = 1 + theta_1 z + ... + theta_q z^q  is the MA polynomial.
# We assume phi(z) and theta(z) have no common factors.

# Simulate ARMA(2, 2):
#     X_t = 0.8 X_{t-1} - 0.6 X_{t-2} + 0.7 eps_{t-1} + 0.4 eps_{t-2} + eps_t
# where eps_t ~ iidN(0, 1), sample size N = 200.
N = 200
X = np.zeros(N)
phi_1, phi_2 = 0.8, -0.6
theta_1, theta_2 = 0.7, 0.4
epsilon = ss.norm.rvs(loc=0, scale=1, size=N, random_state=42)
for t in range(2, N):
    X[t] = (phi_1 * X[t - 1] + phi_2 * X[t - 2]
            + theta_1 * epsilon[t - 1] + theta_2 * epsilon[t - 2] + epsilon[t])

# Plot the sample path
plt.figure(figsize=(6, 3))
plt.plot(X, color='C4')
plt.title('ARMA(2, 2) Sample Path')
plt.xlabel('N')
plt.grid(True)
plt.show()


# -----------------------------------------------------------------------------
# 2.3.2 Causality
# -----------------------------------------------------------------------------
#
# Causality means the current X_t can be expressed as a function of past values
# and past shocks. An ARMA model is causal if the AR part ensures X_t depends
# only on its own past values.
#
# For causality, the roots of the AR characteristic equation must lie outside
# the unit circle in the complex plane:
#
#     phi(B) = 1 - phi_1 B - phi_2 B^2 - ... - phi_p B^p = 0
#
# If all roots have modulus > 1, the model is causal and X_t can be written as
# an infinite MA representation:
#
#     X_t = sum_{j=0}^{inf} psi_j eps_{t-j}

# Test for causality of the ARMA(2, 2) example above
ar_coefs = np.array([0.6, -0.8, 1])        # 0.6*B^2 - 0.8*B + 1 = 0
ar_roots = np.roots(ar_coefs)              # Find the roots of the polynomial
is_causal = all(np.abs(ar_roots) > 1)     # Check if all roots are outside the unit circle

print(f"Is causal: {is_causal}")


# -----------------------------------------------------------------------------
# 2.3.3 Invertibility
# -----------------------------------------------------------------------------
#
# Invertibility means the current shock eps_t can be expressed as a function
# of past values of X_t. An ARMA model is invertible if the MA part ensures
# eps_t depends only on past values of X_t.
#
# For invertibility, the roots of the MA characteristic equation must lie
# outside the unit circle:
#
#     theta(B) = 1 + theta_1 B + theta_2 B^2 + ... + theta_q B^q = 0
#
# If all roots have modulus > 1, the model is invertible and eps_t can be
# written as an infinite AR representation:
#
#     eps_t = sum_{j=0}^{inf} pi_j X_{t-j}

# Test for invertibility of the ARMA(2, 2) example above
ma_coefs = np.array([0.4, 0.7, 1])             # 0.4*B^2 + 0.7*B + 1 = 0
ma_roots = np.roots(ma_coefs)                  # Find the roots of the polynomial
is_invertible = all(np.abs(ma_roots) > 1)      # Check if all roots are outside the unit circle

print(f"Is invertible: {is_invertible}")


# =============================================================================
# 3. Estimation Methods
# =============================================================================
#
# An ARMA model requires the time series to be stationary. Before estimation,
# check stationarity (e.g., ADF test or KPSS test).
#
# The order (p, q) is unknown and needs to be determined:
#   - Using ACF and PACF plots
#   - Using information criteria such as AIC, BIC, etc.
#
# Note: ARIMA = AutoRegressive Integrated Moving Average. We build an
# ARIMA(p, d, q) model by building an ARMA(p, q) model on the differenced
# series.
#
# Common parameter estimation approaches:
#   - Innovations algorithm
#   - Method of moments
#   - Conditional least squares
#   - Maximum likelihood
# (See section 4.2 in "Applied Time Series Analysis and Forecasting with Python")


# =============================================================================
# 4. Forecasting
# =============================================================================
#
# Let {X_{1:n}} be the known data used to forecast future values beyond the
# present n (the forecast origin). The forecast of X_{n+h} is X_hat_n(h).
# The forecast error is e_n(h) = X_{n+h} - X_hat_n(h).
#
# We use the minimum mean squared error criterion:
#
#     E[e_n(h)^2] = E[(X_{n+h} - X_hat_n(h))^2]
#                 = min_g { E[X_{n+h} - g(X_{1:n})]^2 }
#
# Key results:
#
# 1. X_hat_{n+1} = E(X_{n+1} | X_1, ..., X_n)  for n >= 1.
#    Thus X_hat_n(h) can be recursively computed with the innovations algorithm.
#
# 2. There exist coefficients {phi_{nj}; 1 <= j <= n} such that
#    X_hat_{n+1} = phi_{n1} X_n + ... + phi_{nn} X_1
#    (the best linear predictor for X_{n+1}).
#
# 3. For a causal ARMA(p, q) model with mean zero, one-step-ahead predictors:
#
#    X_hat_{n+1} =
#      0,                                                    if n = 0
#      sum_{j=1}^{n} theta_{nj} (X_{n+1-j} - X_hat_{n+1-j}),
#                                                    if 1 <= n < max(p,q)
#      sum_{i=1}^{p} phi_i X_{n+1-i}
#        + sum_{j=1}^{q} theta_{nj} (X_{n+1-j} - X_hat_{n+1-j}),
#                                                    if n >= max(p,q)
#
#    where theta_{nj} are from the innovations algorithm.
#
# 4. If n > max(p, q), for all h >= 1, the h-step-ahead predictor is:
#
#    X_hat_n(h) = sum_{i=1}^{p} phi_i X_hat_n(h-i)
#                 + sum_{j=h}^{q} theta_{n+h-1,j} (X_{n+h-j} - X_hat_{n+h-j})
#
#    where X_hat_{n+h-j} is a one-step-ahead predictor.
