"""
GARCH Models
=============
Exploration of Generalized Autoregressive Conditional Heteroskedasticity (GARCH)
models, including ARCH(p) and GARCH(p,q) formulations, simulation of sample paths,
and a discussion of estimation and diagnostic testing procedures.

Reference: Chapter 6 from "Applied Time Series Analysis and Forecasting with Python"
(Huang & Petukhina, 2022).

Source: "quantitative-finance-notebooks" collection.
"""

import numpy as np
import scipy.stats as ss
import matplotlib.pyplot as plt

# ============================================================================
# 1. Features of Financial Returns Series
# ============================================================================
#
# Fat (heavy) tails:
#   The distribution density function of returns often has fatter (heavier)
#   tails than the tails of the corresponding normal distribution density.
#
# ARCH effect:
#   Although the return series can often be seen as a white noise, its squared
#   (and absolute) series may usually be autocorrelated, and these
#   autocorrelations are hardly negative.
#
# Volatility clustering:
#   Large changes in returns tend to cluster in time, and small changes
#   tend to be followed by small changes.
#
# Asymmetry:
#   The distribution of asset returns is slightly negatively skewed. One
#   possible explanation could be that traders react more strongly to
#   unfavourable information than favourable information.


# ============================================================================
# 2. ARCH Models
# ============================================================================
#
# Autoregressive Conditional Heteroskedasticity (ARCH) models can capture
# some of the features of financial returns series outlined above.
#
# An ARCH(p) model with order p >= 1 is of the form:
#
#   X_t = sigma_t * epsilon_t
#   sigma_t^2 = omega + alpha_1 * X_{t-1}^2 + ... + alpha_p * X_{t-p}^2
#
# where omega >= 0, alpha_i >= 0, alpha_p > 0 are constants,
# epsilon_t ~ iid(0, 1), and epsilon_t is independent of {X_k; k <= t-1}.
#
# By definition, sigma_t^2 (and sigma_t) is independent of epsilon_t.
# Usually it is further assumed that epsilon_t ~ N(0, 1). Sometimes,
# however, we need to further suppose that epsilon_t follows a standardized
# (skew) Student's T distribution or a generalized error distribution in
# order to capture more features of a financial time series.
#
# Let F_s denote the information set generated by {X_k; k <= s}, namely
# the sigma field sigma(X_k; k <= s). It is easy to see that F_s is
# independent of epsilon_t for any s < t. Then:
#
#   E(X_t | F_{t-1}) = sigma_t * E(epsilon_t) = 0
#
#   Var(X_t | F_{t-1}) = E(X_t^2 | F_{t-1}) = sigma_t^2
#
# This implies that sigma_t^2 is the conditional variance of X_t and it
# evolves according to previous values of {X_k; t-p <= k <= t-1} like
# an AR(p) model.
#
# --- ARCH(1) Example ---
#
# Consider the ARCH(1) model:
#
#   X_t = sigma_t * epsilon_t
#   sigma_t^2 = omega + alpha_1 * X_{t-1}^2
#
# The unconditional mean:
#   E(X_t) = E(sigma_t * epsilon_t) = E(sigma_t) * E(epsilon_t) = 0
#
# The ARCH(1) model can be expressed as:
#   X_t^2 = omega + alpha_1 * X_{t-1}^2 + eta_t
#
# where eta_t = sigma_t^2 * (epsilon_t^2 - 1) is a white noise. Hence if
# 0 <= alpha_1 <= 1, this is a stationary AR(1) model for X_t^2.
#
# The unconditional variance:
#   Var(X_t) = E(X_t^2) = omega / (1 - alpha_1)
#
# For h > 0:
#   E(X_{t+h} * X_t) = 0


# ============================================================================
# 2a. ARCH(1) Simulation
# ============================================================================
# Given an ARCH(1) model:
#   X_t = sigma_t * epsilon_t
#   sigma_t^2 = 0.1 + 0.2 * X_{t-1}^2
# where epsilon_t ~ iid N(0, 1), simulate a sample of size 200.

# Simulate a sample path from the ARCH(1) model given above
N = 200
X = np.zeros(N)
sigma_squared = np.zeros(N)
omega = 0.1
alpha_1 = 0.2
epsilon = ss.norm.rvs(loc=0, scale=1, size=N, random_state=42)
for t in range(1, N):
    sigma_squared[t] = omega + alpha_1 * X[t-1]**2
    X[t] = np.sqrt(sigma_squared[t]) * epsilon[t]

# Plot the sample path of X and sigma_squared
fig, axes = plt.subplots(1, 2, figsize=(10, 3))
axes[0].plot(X)
axes[0].set_title('ARCH(1) Sample Path of X')
axes[0].set_xlabel('N')
axes[0].grid(True)
axes[1].plot(sigma_squared, color='C1')
axes[1].set_title('ARCH(1) Sample Path of Conditional Variance')
axes[1].set_xlabel('N')
axes[1].grid(True)
plt.tight_layout()
plt.show()


# ============================================================================
# 3. GARCH Models
# ============================================================================
#
# A natural idea for extending the ARCH model is to include a moving average
# part in the model, which is similar to the extension from an AR model to
# an ARMA model.
#
# A GARCH(p, q) model with order (p >= 1, q >= 0) is of the form:
#
#   X_t = sigma_t * epsilon_t
#   sigma_t^2 = omega + sum_{i=1}^{p} alpha_i * X_{t-i}^2
#                      + sum_{j=1}^{q} beta_j  * sigma_{t-j}^2
#
# where omega >= 0, alpha_i >= 0, beta_j >= 0, alpha_p > 0, beta_q > 0
# are constants, epsilon_t ~ iid(0, 1), and epsilon_t is independent of
# {X_k; k <= t-1}.
#
# In practice, the ARCH(p) model will provide an adequate fit only if the
# order p is large. By allowing past volatilities to affect the present
# volatility, a more parsimonious model may result.
#
# If X_t is a GARCH(p, q) process and sum alpha_i + sum beta_j < 1, then:
#
# (1) X_t^2 follows the ARMA(m, q) model:
#     X_t^2 = omega + sum_{i=1}^{m} (alpha_i + beta_i) * X_{t-i}^2
#                    + eta_t - sum_{j=1}^{q} beta_j * eta_{t-j}
#     where alpha_i = 0 for i > p, beta_j = 0 for j > q, m = max(p, q),
#     and eta_t = sigma_t^2 * (epsilon_t^2 - 1).
#
# (2) X_t is a white noise with:
#     E(X_t) = 0
#     E(X_{t+h} * X_t) = 0 for any h != 0
#     Var(X_t) = omega / (1 - sum_{i=1}^{m} (alpha_i + beta_i))
#
# (3) sigma_t^2 is the conditional variance of X_t:
#     E(X_t | F_{t-1}) = 0
#     sigma_t^2 = Var(X_t | F_{t-1})
#
# If a time series Y_t is autocorrelated and has ARCH effect, then a GARCH
# model that can capture the features of Y_t should be of the form:
#
#   Y_t = f(Z_t, Y_{t-1}, X_{t-1}, Y_{t-2}, X_{t-2}, ...) + X_t
#   X_t = sigma_t * epsilon_t
#   sigma_t^2 = omega + sum alpha_i * X_{t-i}^2 + sum beta_j * sigma_{t-j}^2
#
# where the top part is the "mean equation" and the bottom line is the
# "volatility (variance) equation", and Z_t represents exogenous regressors.
# If Y_t is a return series, then typically Y_t = r + X_t where r is a
# constant representing expected returns.


# ============================================================================
# 3a. GARCH(1,1) Simulation
# ============================================================================
# Given a GARCH(1, 1) model:
#   X_t = sigma_t * epsilon_t
#   sigma_t^2 = 0.1 + 0.2 * X_{t-1}^2 + 0.6 * sigma_{t-1}^2
# where epsilon_t ~ iid N(0, 1), simulate a sample of size 200.

# Simulate a sample path from the GARCH(1, 1) model given above
N = 200
X = np.zeros(N)
sigma_squared = np.zeros(N)
omega = 0.1
alpha_1 = 0.2
beta_1 = 0.6
epsilon = ss.norm.rvs(loc=0, scale=1, size=N, random_state=42)
for t in range(1, N):
    sigma_squared[t] = omega + alpha_1 * X[t-1]**2 + beta_1 * sigma_squared[t-1]
    X[t] = np.sqrt(sigma_squared[t]) * epsilon[t]

# Plot the sample path of X and sigma_squared
fig, axes = plt.subplots(1, 2, figsize=(10, 3))
axes[0].plot(X, color='C2')
axes[0].set_title('GARCH(1, 1) Sample Path of X')
axes[0].set_xlabel('N')
axes[0].grid(True)
axes[1].plot(sigma_squared, color='C3')
axes[1].set_title('GARCH(1, 1) Sample Path of Conditional Variance')
axes[1].set_xlabel('N')
axes[1].grid(True)
plt.tight_layout()
plt.show()


# ============================================================================
# 4. Estimation and Testing
# ============================================================================
#
# It is always a good idea to transform a given (asset) price series into
# the log return series. There are four basic steps toward estimation of a
# GARCH model for a given time series data Y_t:
#
# Step 1: If Y_t is autocorrelated, build an appropriate mean model (e.g.,
#   ARMA) to remove any autocorrelation. The residual series X_t of the
#   mean equation should be a white noise.
#
# Step 2: Test whether X_t has an ARCH effect. If yes, continue to build
#   an adequate volatility model; otherwise, stop. The squared residual
#   series X_t^2 should follow an ARMA model if X_t is a GARCH process.
#   Examine X_t^2 by its (P)ACF and the Ljung-Box test. If X_t^2 is
#   significantly autocorrelated, then X_t should have an ARCH effect.
#
# Step 3: Use volatility models to fit X_t if the ARCH effect is
#   statistically significant, to obtain the estimated volatility equation.
#   In most cases, only GARCH models with lower order (p <= 2, q <= 2) are
#   used and fitted well.
#
# Step 4: Diagnostically check the fitted model and refine if necessary.
#   For a properly specified GARCH model, the "standardized" residual
#   series eps_tilde_t = X_t / sigma_tilde_t should be iid N(0, 1).
#   Diagnose the adequacy of a fitted GARCH model by examining eps_tilde_t.
#   Note that sigma_tilde_t is an estimate of the conditional volatility
#   sigma_t, not an estimate for the standard deviation of X_t.
